### ISSUE TITLE
3.8.1.1 vehicle definition

### ISSUE THREAD

**Issue by burespe1** [ISO-TC204/iso14812#10]
During the meeting (04/08/2019) we have discussed the problem of **further specification of the term vehicle**. There is a number of different perspectives rendering a number of different views. View: high/mid/low speed vehicle being one of them. Other perspectives might be distinction of vehicles by load/passenger capacity, number of wheels, off-road/on road ... Specification of those views is difficult without the feedback from the low level term users.

The proposal is to create the list of vehicle attributes to draw these subclasses from.

**Comment by k-vaughn** [comment]
We have revised the definition under the Vehicle terms (3.8) and are proposing that many of these terms be moved to a later release; we are proposing to only address the terms currently under 3.8.1-3.8.5 dealing with components, automation, connectivity, and perhaps design speed and classifications. This will be discussed further on our next call.

**Comment by k-vaughn** [comment]
SAE J3194:2019 was recently published and defines ultra-low speed, low speed, and medium speed. I have revised the model to be consistent with these terms.
