### ISSUE TITLE
3.2.1.1 ITS application

### ISSUE THREAD

**Issue by MasanoriMisumi** [ISO-TC204/iso14812#21]
In the idea of "ITS", there are external areas outside  "C-ITS". 
In this regard, ITS application is not necessarily limited to "interoperability design".
My proposal, as an example, is as follows:

    an application designed for an ITS service

**Comment by k-vaughn** [comment]
The WG discussed this comment and determined that the proposed definition is not sufficient as it does not adequately define what is meant by a "application" or "design" (i.e., it could be interpreted to be a low-level design).
The group further determined that the current draft definition "interoperability design for an ITS service" does not imply any additional meaning beyond your proposal (i.e., it merely consrains the meaning by clearly indicating that the "design" is limited to the "interoperability" characteristics and not low-level details.
It was suggested that the confusion may arise with the belief that "interoperability" implies publicly available, but this is not the case. We have added a note to the entry to clarify this as follows: "The interoperability design does not have to be publicly available; it may be a proprietary design."
Please let us know if this adequately addresses your comment.

**Comment by k-vaughn** [comment]
This comment is closed due to no response and the need to move the standard for a committee level comment.
