### ISSUE TITLE
3.7.6.1 vehicle on-board equipment

### ISSUE THREAD

**Issue by MasanoriMisumi** [ISO-TC204/iso14812#22]
Vehicle on-board equipment is not limited for the C-ITS services.
My proposal, as an example, is as follows:

vehicle system that provides the on-board functions including supporting for C-ITS services

**Comment by k-vaughn** [comment]
The proposed definition is problematic as it does not adequately delineate the scope of functions provided nor does it required C-ITS functionality; in essence, it includes any onboard functions (i.e., "vehicle system that provides the onboard functions") which is overly broad. 

WG 1 agrees that the C-ITS restriction is unnecessarily narrow as there may be functions that are not technically "cooperative", thus our counter proposal is to revise the draft definition to be "vehicle system that provides the onboard functions necessary to support the ITS services supported by the vehicle"

We have also added a note as follows: "The vehicle onboard equipment may also perform other functions."

**Comment by k-vaughn** [comment]
This comment is being closed due to no response and the need to move the standard for a committee level comment.
