### ISSUE TITLE
Connected vehicle and related

### ISSUE THREAD

**Issue by tlusco** [ISO-TC204/iso14812#25]
The definition for 'Connected vehicle' is "A vehicle that is equipped with vehicle onboard equipment (OBE) that is active and operational."
The supporting definition for OBE is "vehicle system that provides the onboard functions necessary to support the ITS services supported by the vehicle"
The supporting definition for Vehicle System is "ITS component that is installed as a component of a vehicle"
The supporting definition for ITS Component is "physical object that has been assigned one or more ITS functional objects"

No where in there do we talk about communications. We must mention communications if we are defining a device to be "connected."

ITS services should be linked. That definition is "<ITS> performance of one or more tasks to fulfil an ITS user need for an ITS user". We can follow the chain down to "technology system" that finally talks about communications: "system that is comprised of information, communication, sensor, and control technologies"

The definition of technology system is somewhat helpful, but not enough. First, not every technology system will have those four aspects. So the 'and' should become an 'and/or'. 

An ITS station must include communications. Unfortunately our definition does not include mention of that either. I can accept that, since the definition pushes the ITS-S reference architecture, which would force the reader to go to 21217. Unfortunately, this means we still have no definition of connected vehicle that includes any aspect of connectivity.

I propose:
Connected Vehicle: A vehicle that is equipped with vehicle onboard equipment that is active and operational, and includes the means to send and receive data to and from other connected devices.

We would then need a definition of a connected device, which I propose would be "A physical object that includes means to send and receive data to/from other physical objects"

**Comment by k-vaughn** [comment]
connected - characteristic of an entity that is equipped with enabled (i.e., on) and operational (i.e., no errors) electronic communication technologies to support ITS services, including the means to send and receive data to and from other connected entities
Example: connected vehicle, connected device

Revise the diagram to show that "connected" can be an attribute of a vehicle

OBE - vehicle system that provides the onboard functions and electronic communications necessary to support the ITS services supported by the vehicle, including the means to send and receive data to and from equipment outside of the vehicle

technology system - system that is comprised of one or more of information, communication, sensor, and control technologies
