### ISSUE TITLE
3.3.1 shoulder uses deprecated term right-of-way

### ISSUE THREAD

**Issue by benevellid** [ISO-TC204/iso14812#28]
The definition of shoulder is shown as:
lane between the edge of a carriageway and any slope or edge of right-of-way
Suggest removing the deprecated term right-of-way as follows:
lane between the edge of a carriageway and any slope or edge of easement

**Comment by k-vaughn** [comment]
Overcome by events: At the Singapore meeting we decided to move closer to the PIARC definition and we added the term "roadside" to talk about the area to the easement
