### ISSUE TITLE
3.3.1 easement definition 

### ISSUE THREAD

**Issue by benevellid** [ISO-TC204/iso14812#29]
The easement definition is:
stretch of land reserved for transportation purposes
Suggest adopting the following:
land reserved for transportation purposes
Issue is whether the definition addresses other transportation modes, such as water travel, air travel ground facilities, can be treated similarly. Does a river channel a valid example of an easement? This definition seems to conflict with the definition of easement in the Merriam-Webster dictionary:
Definition of easement
1 : an act or means of easing or relieving (as from discomfort)
2 : an interest in land owned by another that entitles its holder to a specific limited use or enjoyment also : an area of land covered by an easement

**Comment by k-vaughn** [comment]
Actually the second definition of easement applies here, just not in the traditional interpretation (but legal precedent seems to use it). It is in fact, "an area of land covered by" an "interest (i.e., right to travel) in land owned by another (e.g., the government - although in many jurisdictions, roads are technically on private land) that entitles its holder (i.e., the traveler) to a specific limited use (i.e., travel).

Within the scope of ITS, I have no problem adopting your definition.
