### ISSUE TITLE
Roadway component terms class diagram shows roadway users

### ISSUE THREAD

**Issue by benevellid** [ISO-TC204/iso14812#32]
The class diagram shows roadway is used by motor vehicles.  Roadways are also used by pedestrians, cyclists.  Suggest adding these other users.

**Comment by k-vaughn** [comment]
Unclear what class diagram you are referring to, but it does not appear to be in the current draft

**Comment by k-vaughn** [comment]
Ack, sorry, I found the reference; but it has been removed in the current working version. Adding other users would make this diagram (roadway component terms) way too busy
