### ISSUE TITLE
Roadway component terms class diagram lane relationship

### ISSUE THREAD

**Issue by benevellid** [ISO-TC204/iso14812#33]
There seems to be an inconsistent relationship regarding lane.  As one or more travel lanes constitutes a traveled way, consider adjusting the lane definition to relate to traveled way rather than easement.

**Comment by k-vaughn** [comment]
There does not appear to be any inconsistency and circular definitions are not allowed. Defining "lane" using the term "traveled way" would create a circle (lane -> traveled way -> travel lane -> lane). Further, defining lane in the terms of a travelled way would omit some types of lanes (e.g., non-"travelled lanes" such as shoulders, cycle lanes, footways, etc.)
