### ISSUE TITLE
Cannot access EAP or XMI model file

### ISSUE THREAD

**Issue by SPowley** [ISO-TC204/iso14812#36]
Hi,

I'm reviewing ISO/DTS 14812 and was directed to https://github.com/isotc204/14812/projects by Annex D. This link is broken, but I found the site at https://github.com/ISO-TC204/iso14812 (note the link in the standard is missing a hyphen). This in turn led me to the Wiki at https://github.com/ISO-TC204/iso14812/wiki, which had different URIs for the EAP and XMI files, namely https://github.com/ISO-TC204/iso14812/blob/development/14812.eap and https://github.com/ISO-TC204/iso14812/blob/development/14812.xml Both these links are also broken, just leading to 404 pages. I can browse the website version at https://iso-tc204.github.io/iso14812/development/ but this is not as useful to me as the EAP or XMI.

I congratulate you on the adoption of this modelling approach, it's something that is sorely missing in standards development and I would be keen to explore further. I'm trying to introduce the same thing in ISO SC 32/WG 11 in the context of developing ISO 21434 "Road vehicles - Cybersecurity Engineering", on which committee I am an expert. It would be excellent to have access to this model as an exemplar.

Please can you advise the correct locations for the model files and update links in the draft standard and on GitHub pages.

Thanks in advance,

Stephen

**Comment by k-vaughn** [comment]
Thank you for pointing this out. I admit that I am not great at Git and I am still learning how to synchronize everything the way that I want. I have now corrected the issues and the latest files are posted as advertised (on the development branch)

FYI: In the next release of this standard we expect to convert the model from the current ISO 24156-1 format (which uses UML class diagrams with named associations and arrow adornments) to ODM 1.1 (where the names are moved to role names and the directional adornment is converted into a directional association). These minor changes should allow an automated conversion to RDF to better support ontology tools.
