### ISSUE TITLE
data element

### ISSUE THREAD

**Issue by MarcoSzewczyk** [ISO-TC204/iso14812#40]
Should this be 'data element concept'?
"A data element is the basic unit of identifiable and definable information created by combining a data element concept and a value domain". The above is more clear in definition and consistent with Australian Metadata definition.

**Comment by k-vaughn** [comment]
It is unclear why you think that this term should be "data element concept". 

"data element concept" is generally understood to mean "concept (3.2.18) that is an association (3.1.2) of a property (3.2.100) with an object class (3.2.88)" [ISO/IEC 11179-1]. In other words, it is a property of a specific class, independent of any representational form.

The definition proposed in DTS 14812 appears to be semantically equivalent to what you suggest. In other words, both definitions seem to define a "data element" to be a "property about a class" (i.e., a data element concept) combined with a "value domain" (i.e., its representational form). 

The precise wording of our definition is based on ISO 14817-1, which is the long-term standard for defining data concepts in ISO/TC 204, updated based on a more precise concept model that ensures that the definition does not contain any circular reference.

We will discuss this term in a joint meeting with WG1 and WG5 (date TBD)

**Comment by k-vaughn** [comment]
The group adopted the following definition:
**data element**
unit of data that is considered in context to be indivisible and which includes an unambiguous representational form
Note 1 to entry: The definition states that a data element is “indivisible” in some context. This means it is possible that a data element considered indivisible in one context (e.g., location) may be divisible in another context (e.g., latitude, longitude, and elevation).
