### ISSUE TITLE
field system 

### ISSUE THREAD

**Issue by MarcoSzewczyk** [ISO-TC204/iso14812#42]
'Roadside system' would be the better term for what is described in the definition. Roadside equipment is then defined as the components that make up the roadside system.

**Comment by k-vaughn** [comment]
Not all field systems are located along a road. For example, there are various types of systems that are deployed in pedestrian environments. The term "Field system" has been used for a prolonged period in many environments. Nonetheless, we will add this as a WG1 topic to discuss.

**Comment by k-vaughn** [comment]
The WG agreed to add "roadside system" as another preferred term, but as some field systems are not along the roadside, the primary term is still "field system"
