### ISSUE TITLE
vehicle onboard equipment and vehicle onboard unit

### ISSUE THREAD

**Issue by MarcoSzewczyk** [ISO-TC204/iso14812#43]
I feel this needs a discussion and better definition as there is still a lack of clarity between vehicle onboard equipment and vehicle onboard unit.

**Comment by k-vaughn** [comment]
These terms will be discussed in a joint meeting between WG1, WG5 and WG18 (to be scheduled)

**Comment by k-vaughn** [comment]
The group agreed that the OBU is "part of OBE that provides wireless connectivity to other ITS components external to the vehicle"
