### ISSUE TITLE
ISO/IEC/IEEE 42010 reference missing in 3.1.1

### ISSUE THREAD

**Issue by tlusco** [ISO-TC204/iso14812#6]
Most of the definitions in 3.1.1 should reference ISO 42010:2011 as that is the normative source of the definitions.

**Comment by k-vaughn** [comment]
The definitions that are derived from ISO 42010 already reference this as the source; "architecture model", "element", and "system" are not defined in ISO 42010, but are discussed within the standard, appear in the concept diagrams contained in the standard, and appear in definitions of other terms within the standard. As such, it seems as if these terms should be defined, but we have more flexibility in the exact text of the definition.

**Comment by tlusco** [comment]
I browsed the HTML version of these definitions and could not find the reference to 42010. Perhaps I'm missing something as a GitNewbie....

**Comment by k-vaughn** [comment]
Will investigate to see if there is a way to move the source attribute into the main body of the term detail page on the website

**Comment by k-vaughn** [comment]
Investigations revealed that there is no easy way to do this (i.e., without creating our own website generator). As an alternative, I've added text to the main body that directs the reader to the tabs for more information.
