### ISSUE TITLE
3.1.1 Element definition

### ISSUE THREAD

**Issue by tlusco** [ISO-TC204/iso14812#7]
This is the only item within 3.1.1 that doesn't trace to 42010. I'm not sure why we need this term, but if we do need a term for a component member of an architecture, I submit the term 'artifact' in place of element. 

'Element' is a defined term within the US architecture effort, and refers to instantiations of architecture artifacts. That is, an artifact is the reference term, but element is the instance term. So for example, we have an artifact "Traffic Management Center(TMCs)", and a given regional architecture may define three TMC elements; e.g. Northern TMC, Western TMC, Southern TMC.

**Comment by tlusco** [comment]
We need to find a way to get EA's tree display to order properly. Right now it shows 3.1.10 before 3.1.2

**Comment by k-vaughn** [comment]
While ISO 42010 does not define the term "element" it does use the term as a part of its definition of "architecture" and the body of the standard does provide a complete discussion of elements (a.k.a., "AD element" or "architecture description element"). Given its integral use within this context, it seems to me as if it should be a defined term - but more importantly, we should avoid creating conflicting definitions. We could, however, create separate domain definitions by preceding the text of the definition with "<architecture description>"

**Comment by tlusco** [comment]
So if we must define it, I submit that the definition should be tightened slightly. As written, a viewpoint is an element, and I don't think that's what we want. I think we mean something that appears in a view; i.e. a model artifact. So perhaps "component member of a model included in an architecture view", or simply "component member of a model"

**Comment by k-vaughn** [comment]
Revised the definition to read "component member of a model included in an architecture view"
