### ISSUE TITLE
3.1.10 & 3.1.11

### ISSUE THREAD

**Issue by ozakiharuo** [ISO-TC204/iso14812#9]
Comparing two diagrams, I do not fully understand the proper choices and terms of the concepts. 
 service provider --- (service) consumer or user
 (consumer) need -- user need, etc.
Is there a  'need' of some rationale ?
Next two may be amendments relating to 3.1.10.
 Title of the diagram is Service terms - Generic.
 Source Value of "entity" is [Source: ISO 17185-1:2014, 3.4].

**Comment by k-vaughn** [comment]
We revised the models to use more consistent terms among these models

**Comment by ozakiharuo** [comment]
Thank you, they have become pretty much consistent.
